[server]
    Address =":8199"
    ServerAgent= "go-gf-demo"
    # Logging配置
    LogPath             = "./log/server"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
    LogStdout           = true               # 日志是否输出到终端。默认为true
    ErrorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    ErrorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
    ErrorLogPattern     = "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    AccessLogEnabled    = false              # 是否记录访问日志。默认为false
    AccessLogPattern    = "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

title = "TOML 例子"

[db]
    [[db.def]]
        host     = "127.0.0.1"
        port     = "11232"
        user     = "root"
        pass     = "qwe123!@#"
        name     = "cloudproject"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"
    [[db.def]]
        host     = "127.111.0.1"
        port     = "11232"
        user     = "root"
        pass     = "qwe123!@#"
        name     = "cloudproject"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"

[database]
    [database.defaultdemo]
        link = "mysql:root:qwe123!@#@tcp(127.0.0.1:3306)/cloudproject"
        role         = "master"
        # debug        = "false"
        debug        = "true"
        # 空跑特性 结合调试模式和日志输出一起使用
        dryrun       = 0
        weight       = "100"
        prefix       = ""
        charset      = "utf8"
        linkinfo     = ""
        maxIdle      = "10"
        maxOpen      = "100"
        maxLifetime  = "30"
    [database.logger]
        Path   = "./log/dbsql"
        Level  = "all"
        Stdout = false
        # { "database": { "logger": { "Stdout": false } } }