[db2]
    [[db2.def]]
        host     = "127.0.0.1"
        port     = "3306"
        user     = "root"
        pass     = "qwe123!@#"
        name     = "cloudproject"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"